version: '3.4'

services:
  financialcontrol.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__FinancialControlContext=Server=sqldata;Database=FinancialControl;User Id=sa;Password=Pass@word
      - MongoDb__ConnectionString=${MONGODB_CONNECTIONSTRING:-mongodb://nosqldata}
      - MongoDb__DatabaseName=${MONGODB_DATABASENAME:-FinancialControl}
    ports:
      - "5101:80"

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "12433:1433"

  nosqldata:
    ports:
      - "27017:27017"