version: '3.4'

services:
  financialcontrol.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80      
      - ConnectionStrings__FinancialControlContext=Server=sqldata;Database=FinancialControl;User Id=sa;Password=Pass@word
      - MongoDb__ConnectionString=${MONGO_DB}
      - MongoDb__DatabaseName=FinancialControl
    ports:
      - "5101:80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "12433:1433"
    volumes:
      - financialcontrol-sqldata:/var/opt/mssql

  nosqldata:
    ports:
      - "27017:27017"
    volumes:
      - financialcontrol-nosqldata:/data/db

volumes:
  financialcontrol-nosqldata:
    driver: local
  financialcontrol-sqldata:
    driver: local