version: '3.4'

services:
  financialcontrol.api:
    image: ${DOCKER_REGISTRY-}financialcontrolapi
    build:
      context: .
      dockerfile: src/FinancialControl.Api/Dockerfile
    depends_on:
      - sqldata
      - nosqldata
      
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04

  nosqldata:
    image: mongo